const HEVY_BASE = 'https://api.hevyapp.com'

// exercisedb apiMuscle → Hevy primary_muscle_group
const HEVY_MUSCLE = {
  pectorals:    'chest',
  delts:        'shoulders',
  biceps:       'biceps',
  triceps:      'triceps',
  forearms:     'forearms',
  abs:          'abdominals',
  lats:         'lats',
  'upper back': 'upper_back',
  spine:        'lower_back',
  traps:        'traps',
  glutes:       'glutes',
  quads:        'quadriceps',
  hamstrings:   'hamstrings',
  calves:       'calves',
}

async function hevyFetch(path, apiKey, options = {}) {
  const res = await fetch(`${HEVY_BASE}${path}`, {
    ...options,
    headers: {
      'api-key': apiKey,
      'Content-Type': 'application/json',
      ...(options.headers || {}),
    },
  })
  if (!res.ok) {
    const text = await res.text().catch(() => '')
    let msg = `${res.status}`
    try { const j = JSON.parse(text); msg = j.message ?? j.error ?? msg } catch {}
    throw new Error(msg)
  }
  return res.json()
}

export async function fetchAllHevyTemplates(apiKey) {
  const templates = []
  let page = 1
  while (true) {
    const data = await hevyFetch(`/v1/exercise_templates?page=${page}&pageSize=100`, apiKey)
    const items = data.exercise_templates ?? []
    templates.push(...items)
    if (page >= (data.page_count ?? 1) || items.length < 100) break
    page++
  }
  return templates
}

export async function fetchHevyUser(apiKey) {
  return hevyFetch('/v1/user/info', apiKey)
}

export async function createHevyRoutine(apiKey, routine) {
  return hevyFetch('/v1/routines', apiKey, {
    method: 'POST',
    body: JSON.stringify({ routine }),
  })
}

// Normalize a name for fuzzy matching: lowercase, strip equipment words + punctuation
function normalize(name) {
  return name
    .toLowerCase()
    .replace(/\([^)]*\)/g, '')
    .replace(/\b(barbell|dumbbell|cable|machine|kettlebell|smith|bodyweight|body weight|weighted|leverage|ez|olympic|trap bar)\b/g, '')
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

function nameSimilarity(a, b) {
  const wa = normalize(a).split(' ').filter(Boolean)
  const wb = new Set(normalize(b).split(' ').filter(Boolean))
  if (!wa.length || !wb.size) return 0
  return wa.filter(w => wb.has(w)).length / Math.max(wa.length, wb.size)
}

export function matchHevyExercise(exerciseName, apiMuscle, templates) {
  const hevyMuscle = HEVY_MUSCLE[apiMuscle?.toLowerCase()] ?? null
  const pool = hevyMuscle
    ? templates.filter(t => t.primary_muscle_group === hevyMuscle)
    : templates
  const candidates = pool.length > 0 ? pool : templates

  let best = candidates[0] ?? null
  let bestScore = -1
  for (const t of candidates) {
    const score = nameSimilarity(exerciseName, t.title)
    if (score > bestScore) { bestScore = score; best = t }
  }
  return best
}

function parseScheme(scheme) {
  const m = scheme.match(/(\d+)\s*[×x]\s*(\d+)/)
  if (!m) return [{ reps: 10 }]
  return Array.from({ length: parseInt(m[1]) }, () => ({ reps: parseInt(m[2]) }))
}

export function buildHevyRoutine(exerciseItems, workoutType, title) {
  return {
    title: title || 'Muscle Picasso Workout',
    folder_id: null,
    notes: 'Generated by Muscle Picasso 🎨',
    exercises: exerciseItems.map(({ templateId, scheme }) => ({
      exercise_template_id: templateId,
      superset_id: null,
      rest_seconds: workoutType === 'calisthenics' ? 60 : 90,
      notes: '',
      sets: parseScheme(scheme).map(s => ({
        type: 'normal',
        weight_kg: null,
        reps: s.reps,
        distance_meters: null,
        duration_seconds: null,
        custom_metric: null,
      })),
    })),
  }
}
