const HEVY_BASE = 'https://api.hevyapp.com'

// exercisedb apiMuscle → Hevy primary_muscle_group
const HEVY_MUSCLE = {
  pectorals:    'chest',
  delts:        'shoulders',
  biceps:       'biceps',
  triceps:      'triceps',
  forearms:     'forearms',
  abs:          'abdominals',
  lats:         'lats',
  'upper back': 'upper_back',
  spine:        'lower_back',
  traps:        'traps',
  glutes:       'glutes',
  quads:        'quadriceps',
  hamstrings:   'hamstrings',
  calves:       'calves',
}

// exercisedb equipment name → Hevy equipment_category
const HEVY_EQUIPMENT = {
  'barbell':          'barbell',
  'olympic barbell':  'barbell',
  'ez barbell':       'barbell',
  'trap bar':         'barbell',
  'dumbbell':         'dumbbell',
  'kettlebell':       'kettlebell',
  'cable':            'machine',
  'leverage machine': 'machine',
  'smith machine':    'machine',
  'sled machine':     'machine',
  'resistance band':  'resistance_band',
  'band':             'resistance_band',
  'suspension':       'suspension',
  'body weight':      'none',
  'assisted':         'none',
}

function mapEquipment(equipments = []) {
  for (const e of equipments) {
    const key = e.toLowerCase()
    for (const [k, v] of Object.entries(HEVY_EQUIPMENT)) {
      if (key.includes(k)) return v
    }
  }
  return 'other'
}

function mapExerciseType(equipments = []) {
  const eq = equipments.map(e => e.toLowerCase()).join(' ')
  if (eq.includes('body weight') || eq.includes('assisted') || eq.includes('suspension')) return 'bodyweight_reps'
  return 'weight_reps'
}

async function hevyFetch(path, apiKey, options = {}) {
  const res = await fetch(`${HEVY_BASE}${path}`, {
    ...options,
    headers: {
      'api-key': apiKey,
      'Content-Type': 'application/json',
      ...(options.headers || {}),
    },
  })
  if (!res.ok) {
    const text = await res.text().catch(() => '')
    let msg = `${res.status}`
    try { const j = JSON.parse(text); msg = j.message ?? j.error ?? msg } catch {}
    throw new Error(msg)
  }
  return res.json()
}

export async function fetchAllHevyTemplates(apiKey) {
  const templates = []
  let page = 1
  while (true) {
    const data = await hevyFetch(`/v1/exercise_templates?page=${page}&pageSize=100`, apiKey)
    const items = data.exercise_templates ?? []
    templates.push(...items)
    if (page >= (data.page_count ?? 1) || items.length < 100) break
    page++
  }
  return templates
}

export async function fetchHevyUser(apiKey) {
  return hevyFetch('/v1/user/info', apiKey)
}

async function createHevyExerciseTemplate(apiKey, ex, apiMuscle) {
  const body = {
    exercise: {
      title: ex.name,
      exercise_type: mapExerciseType(ex.equipments),
      equipment_category: mapEquipment(ex.equipments),
      muscle_group: HEVY_MUSCLE[apiMuscle?.toLowerCase()] ?? 'other',
      other_muscles: [],
    },
  }
  const data = await hevyFetch('/v1/exercise_templates', apiKey, {
    method: 'POST',
    body: JSON.stringify(body),
  })
  // API returns { id: "..." } or the full template object
  return data.id ?? data.exercise_template?.id ?? data.exercise?.id
}

export async function createHevyRoutine(apiKey, routine) {
  return hevyFetch('/v1/routines', apiKey, {
    method: 'POST',
    body: JSON.stringify({ routine }),
  })
}

// Exact match only: normalize both titles and check equality.
// Returns the template if found, null otherwise.
function normalize(name) {
  return name
    .toLowerCase()
    .replace(/\([^)]*\)/g, '')
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

function findExactTemplate(exerciseName, templates) {
  const target = normalize(exerciseName)
  return templates.find(t => normalize(t.title) === target) ?? null
}

/**
 * Resolve a Hevy exercise_template_id for the given exercise.
 * Uses an exact name match against existing templates; if none found,
 * creates a custom template with the exact exercise name and metadata.
 * The `created` map is a local cache { normalizedName → id } to avoid
 * duplicate creates within a single send operation.
 */
export async function resolveHevyTemplateId(apiKey, ex, apiMuscle, templates, created) {
  const existing = findExactTemplate(ex.name, templates)
  if (existing) return existing.id

  const key = normalize(ex.name)
  if (created[key]) return created[key]

  const id = await createHevyExerciseTemplate(apiKey, ex, apiMuscle)
  created[key] = id
  return id
}

function parseScheme(scheme) {
  const m = scheme.match(/(\d+)\s*[×x]\s*(\d+)/)
  if (!m) return [{ reps: 10 }]
  return Array.from({ length: parseInt(m[1]) }, () => ({ reps: parseInt(m[2]) }))
}

export function buildHevyRoutine(exerciseItems, workoutType, title) {
  return {
    title: title || 'Muscle Picasso Workout',
    folder_id: null,
    notes: 'Generated by Muscle Picasso 🎨',
    exercises: exerciseItems.map(({ templateId, scheme }) => ({
      exercise_template_id: templateId,
      superset_id: null,
      rest_seconds: workoutType === 'calisthenics' ? 60 : 90,
      notes: '',
      sets: parseScheme(scheme).map(s => ({
        type: 'normal',
        weight_kg: null,
        reps: s.reps,
        distance_meters: null,
        duration_seconds: null,
        custom_metric: null,
      })),
    })),
  }
}
